/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.lsug.quota.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the QuotaDailyLog service. Represents a row in the &quot;LSUGQUOTA_QuotaDailyLog&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.lsug.quota.model.impl.QuotaDailyLogModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.lsug.quota.model.impl.QuotaDailyLogImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see QuotaDailyLog
 * @see org.lsug.quota.model.impl.QuotaDailyLogImpl
 * @see org.lsug.quota.model.impl.QuotaDailyLogModelImpl
 * @generated
 */
public interface QuotaDailyLogModel extends BaseModel<QuotaDailyLog> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a quota daily log model instance should use the {@link QuotaDailyLog} interface instead.
	 */

	/**
	 * Returns the primary key of this quota daily log.
	 *
	 * @return the primary key of this quota daily log
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this quota daily log.
	 *
	 * @param primaryKey the primary key of this quota daily log
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the quota daily log ID of this quota daily log.
	 *
	 * @return the quota daily log ID of this quota daily log
	 */
	public long getQuotaDailyLogId();

	/**
	 * Sets the quota daily log ID of this quota daily log.
	 *
	 * @param quotaDailyLogId the quota daily log ID of this quota daily log
	 */
	public void setQuotaDailyLogId(long quotaDailyLogId);

	/**
	 * Returns the day analyzed of this quota daily log.
	 *
	 * @return the day analyzed of this quota daily log
	 */
	public Date getDayAnalyzed();

	/**
	 * Sets the day analyzed of this quota daily log.
	 *
	 * @param dayAnalyzed the day analyzed of this quota daily log
	 */
	public void setDayAnalyzed(Date dayAnalyzed);

	/**
	 * Returns the quota ID of this quota daily log.
	 *
	 * @return the quota ID of this quota daily log
	 */
	public long getQuotaId();

	/**
	 * Sets the quota ID of this quota daily log.
	 *
	 * @param quotaId the quota ID of this quota daily log
	 */
	public void setQuotaId(long quotaId);

	/**
	 * Returns the quota assigned of this quota daily log.
	 *
	 * @return the quota assigned of this quota daily log
	 */
	public long getQuotaAssigned();

	/**
	 * Sets the quota assigned of this quota daily log.
	 *
	 * @param quotaAssigned the quota assigned of this quota daily log
	 */
	public void setQuotaAssigned(long quotaAssigned);

	/**
	 * Returns the quota used of this quota daily log.
	 *
	 * @return the quota used of this quota daily log
	 */
	public long getQuotaUsed();

	/**
	 * Sets the quota used of this quota daily log.
	 *
	 * @param quotaUsed the quota used of this quota daily log
	 */
	public void setQuotaUsed(long quotaUsed);

	/**
	 * Returns the quota status of this quota daily log.
	 *
	 * @return the quota status of this quota daily log
	 */
	public int getQuotaStatus();

	/**
	 * Sets the quota status of this quota daily log.
	 *
	 * @param quotaStatus the quota status of this quota daily log
	 */
	public void setQuotaStatus(int quotaStatus);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(QuotaDailyLog quotaDailyLog);

	public int hashCode();

	public CacheModel<QuotaDailyLog> toCacheModel();

	public QuotaDailyLog toEscapedModel();

	public String toString();

	public String toXmlString();
}